name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: make node
      - run: make dist
      - name: Store distribution package
        uses: actions/upload-artifact@v4
        with:
          name: koala-dist
          path: dist/

  debian:
    name: Build Debian Package
    if: startsWith(github.ref, 'refs/tags/')  # only build Debian package on tag pushes
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: koala-dist
          path: dist/
      - run: sudo apt-get -y install debhelper
      - name: Build Debian package
        run: make deb
      - name: Release Debian Package
        uses: softprops/action-gh-release@v1
        with:
          files: ../*.deb
